### ISSUE TITLE
Support Windows via JRuby - Meta Issue

### ISSUE THREAD

**Issue by nlowe** [gollum/gollum#1044]
We finally got a copy of JRuby on our network, so I thought I'd start testing gollum under windows. I'm going to file individual bug reports for specific things I notice and compile my findings here.

[Installation instructions on the wiki](https://github.com/gollum/gollum/wiki/Installation#windows) will need updated once this issue is closed.

---

This is a meta issue for supporting windows via `JRuby` / `RJGit`
- [x] Page Titles are Incorrect (#1041)
- [x] All Pages View is Incorrect (#1042)
- [x] Page links are rendered Incorrectly (#1043)
- [x] Cannot Create Pages (#1045)
- [x] utf-8 page title incorrect (#1102)
- [x] First page unusable after creation (#1120)
- [x] Pagenames containing colons produce InvalidFilePath exceptions (#1269)
- [x] Sprocket assets cannot be compiled (#1321)

**Comment by dometto** [comment]
Thanks for taking care of this! Some serious issues, but all in not so bad. I guess the extra `:` in the file paths might be due to some manual concatenation of file paths rather than using `::File` somewhere in gollum-lib. FIxing that might go some way to fixing the other issues.

How bad is it when you try to run the tests?

**Comment by techwiz24** [comment]
I still had to manually mark 'test-unit' as a required dependency in the gemfile:

`gollum`:

```text
Finished in 6.335 seconds.
--------------------------------------------------------------------------------
68 tests, 73 assertions, 8 failures, 36 errors, 0 pendings, 0 omissions, 0 notifications
41.1765% passed
--------------------------------------------------------------------------------
10.73 tests/s, 11.52 assertions/s
rake aborted!
SignalException: 1
C:\jruby-1.7.21\bin\rake:23:in `(root)'
Tasks: TOP => test
```

`gollum-lib`:

```text
Finished in 29.258 seconds.
--------------------------------------------------------------------------------
267 tests, 451 assertions, 16 failures, 38 errors, 0 pendings, 0 omissions, 0 notifications
83.5206% passed
--------------------------------------------------------------------------------
9.13 tests/s, 15.41 assertions/s
rake aborted!
SignalException: 1
C:\jruby-1.7.21\bin\rake:23:in `(root)'
Tasks: TOP => test
```

**Comment by techwiz24** [comment]
Also, it seems like the tests don't clean up after themselves:

```text
~/Projects/gollum-lib [master +54 ~1 -0 !]$ git status
On branch master
Your branch is up-to-date with 'origin/master'.

Changes not staged for commit:
  (use "git add <file>..." to update what will be committed)
  (use "git checkout -- <file>..." to discard changes in working directory)

        modified:   Gemfile

Untracked files:
  (use "git add <file>..." to include in what will be committed)

        gollum.lib.tests.log
        test/examples/File_with_checkout20150731-11556-189ngpb
        test/examples/File_with_checkout20150731-11556-1d7x2wq
        test/examples/File_with_checkout20150731-11556-1ttb47t
        test/examples/File_with_checkout20150731-11556-iuyr8m
        test/examples/File_with_checkout20150731-11556-mrmwux
        test/examples/File_with_checkout20150731-7452-1nok97q
        test/examples/File_with_checkout20150731-7452-j8ugfz
        test/examples/File_with_checkout20150731-7452-kz701z
        test/examples/File_with_checkout20150731-7452-mi78gq
        test/examples/File_with_checkout20150731-7452-usidzz
        test/examples/Gollum__Filter__Tags20150731-11556-1ohadep
        test/examples/Gollum__Filter__Tags20150731-7452-xq8woi
        test/examples/Page_Reverting20150731-7452-1i9x90i
        test/examples/Pushing_and_pulling20150731-7452-1n78a0u
        test/examples/Pushing_and_pulling20150731-7452-p9a63z
        test/examples/Renames_directory_traversal20150731-11556-enlp5f
        test/examples/Renames_directory_traversal20150731-7452-14ojosc
        test/examples/Renames_directory_traversal20150731-7452-17yn4di
        test/examples/Renames_directory_traversal20150731-7452-1ewe694
        test/examples/Renames_directory_traversal20150731-7452-1fmpuck
        test/examples/Renames_directory_traversal20150731-7452-1jmnsl6
        test/examples/Renames_directory_traversal20150731-7452-1p282eo
        test/examples/Renames_directory_traversal20150731-7452-1rzqrt7
        test/examples/Renames_directory_traversal20150731-7452-1thfya9
        test/examples/Renames_directory_traversal20150731-7452-1vgekpc
        test/examples/Renames_directory_traversal20150731-7452-1w796m8
        test/examples/Renames_directory_traversal20150731-7452-6vntji
        test/examples/Renames_directory_traversal20150731-7452-9b7rbd
        test/examples/Renames_directory_traversal20150731-7452-bjapd7
        test/examples/Renames_directory_traversal20150731-7452-j5j5xh
        test/examples/Renames_directory_traversal20150731-7452-kw4btl
        test/examples/Renames_directory_traversal20150731-7452-tfm465
        test/examples/Renames_directory_traversal20150731-7452-w6ut05
        test/examples/Unicode_Support20150731-7452-1ay1rxj
        test/examples/Unicode_Support20150731-7452-1vr9tu0
        test/examples/Unicode_Support20150731-7452-b5d1go
        test/examples/Unicode_Support20150731-7452-lx1oeg
        test/examples/Wiki20150731-7452-10yaslh
        test/examples/Wiki20150731-7452-123pb91
        test/examples/Wiki20150731-7452-w3uyf1
        test/examples/Wiki20150731-8044-ocp1d2
        test/examples/Wiki_sync_with_working_directory__filename_contains_whitespace_20150731-11556-1tk20m4
        test/examples/Wiki_sync_with_working_directory__filename_contains_whitespace_20150731-11556-8l1k5l
        test/examples/Wiki_sync_with_working_directory__filename_contains_whitespace_20150731-11556-g0ar7p
        test/examples/Wiki_sync_with_working_directory__filename_contains_whitespace_20150731-11556-gpgz6h
        test/examples/Wiki_sync_with_working_directory__filename_contains_whitespace_20150731-7452-1x70pnu
        test/examples/Wiki_sync_with_working_directory__filename_contains_whitespace_20150731-7452-nr81bn
        test/examples/page_file_dir_option20150731-7452-grwhoj
        test/examples/page_file_dir_option20150731-7452-uh3z3c
        test/examples/page_file_dir_option20150731-8044-1bj5k8o
        test/examples/page_file_dir_option20150731-8044-1ji3fth
        test/examples/page_file_dir_option20150731-8044-rwd06f
        test/examples/with_a_checkout20150731-11556-rb1af6

no changes added to commit (use "git add" and/or "git commit -a")
```

**Comment by SkyCrawl** [comment]
@techwiz24 
Thank you for the report. Would you also mind reporting an example installation procedure on Windows to the [Installation Wiki page](https://github.com/gollum/gollum/wiki/Installation), when you have a bit of time?

**Comment by techwiz24** [comment]
@SkyCrawl Done. I included a note saying that windows support is still in the works and is mostly non-functional at the moment. Its really as simple as installing JRuby and then a `gem install gollum`

**Comment by techwiz24** [comment]
Regarding the first test that fails for `gollum-lib`:

```ruby
test "on disk file, with symlink, raw_data" do
  file = @wiki.file("Data-Two.csv")

  assert_match(/^FirstName,LastName\n/, file.raw_data)
end
```

It doesn't seem that `Pathname` can detect windows symlinks. For this test, I have created the following:

* `C:\SymlinkTest\a.txt`
* `C:\SymlinkTest\b.txt` => softlink to `C:\SymlinkTest\a.txt` (`mklink C:\SymlinkTest\b.txt C:\SymlinkTest\a.txt`)
* `C:\SymlinkTest\c.txt` => hardlink to `C:\SymlinkTest\a.txt` (`fsutil hardlink create C:\SymlinkTest\b.txt C:\SymlinkTest\a.txt`)

```ruby
irb(main):039:0> p = Pathname.new('C:/SymlinkTest/b.txt')
=> <Pathname:C:/SymlinkTest/b.txt>
irb(main):040:0> p
=> <Pathname:C:/SymlinkTest/b.txt>
irb(main):041:0> p.symlink?
=> false
irb(main):046:0> p = Pathname.new('C:/SymlinkTest/c.txt')
=> <Pathname:C:/SymlinkTest/c.txt>
irb(main):047:0> p.symlink?
=> false
```

**Comment by bartkamphorst** [comment]
And what does `p.realpath` return?

**Comment by techwiz24** [comment]
```ruby
~$ irb
io/console not supported; tty will not be manipulated
irb(main):001:0> require 'pathname'
=> true
irb(main):002:0> b = Pathname.new('C:\\SymlinkTest\\b.txt')
=> <Pathname:C:\SymlinkTest\b.txt>
irb(main):003:0> b.realpath
=> <Pathname:C:\SymlinkTest\b.txt>
irb(main):004:0> c = Pathname.new('C:\\SymlinkTest\\c.txt')
=> <Pathname:C:\SymlinkTest\c.txt>
irb(main):005:0> c.realpath
=> <Pathname:C:\SymlinkTest\c.txt>
```

**Comment by bartkamphorst** [comment]
That's unfortunate. Perhaps try JRuby's `File.readlink(path)`?

**Comment by techwiz24** [comment]
Well then...

```ruby
irb(main):001:0> File.readlink('C:\\SymlinkTests\b.txt')
NotImplementedError: readlink unsupported or native support failed to load
        from org/jruby/RubyFile.java:1049:in `readlink'
        from (irb):1:in `evaluate'
        from org/jruby/RubyKernel.java:1079:in `eval'
        from org/jruby/RubyKernel.java:1479:in `loop'
        from org/jruby/RubyKernel.java:1242:in `catch'
        from org/jruby/RubyKernel.java:1242:in `catch'
        from C:/jruby-1.7.21/bin/jirb:13:in `(root)'
```

**Comment by bartkamphorst** [comment]
Hmm. Strange; I thought JRuby would depend on `java.nio.file`, which is supposedly [link aware](https://docs.oracle.com/javase/tutorial/essential/io/links.html) (though I'm starting to become skeptical). We should investigate if we can use that package directly.

**Comment by techwiz24** [comment]
Well that seems to work:

```ruby
irb(main):001:0> import java.nio.file.Files
=> [Java::JavaNioFile::Files]
irb(main):002:0> import java.nio.file.Path
=> [Java::JavaNioFile::Path]
irb(main):004:0> t = "C:\\SymlinkTest\\b.txt"
=> "C:\\SymlinkTest\\b.txt"
irb(main):006:0> import java.nio.file.FileSystems
=> [Java::JavaNioFile::FileSystems]
irb(main):007:0> b = FileSystems.getDefault().getPath('C:\\SymlinkTest', 'b.txt')
=> #<Java::SunNioFs::WindowsPath:0x1e397ed7>
irb(main):008:0> b
=> #<Java::SunNioFs::WindowsPath:0x1e397ed7>
irb(main):010:0> Files.isSymbolicLink(b)
=> true
```

**Comment by bartkamphorst** [comment]
There is [this issue](https://github.com/jruby/jruby/issues/210) which seems related. It very ominously ends with "nor have [I] the time to test on Windows." :fearful: It would be interesting to run the code example with Windows paths and see what happens.

**Comment by techwiz24** [comment]
Well unless I'm initializing it wrong, it seems that symlinks are not supported on windows, as I cannot get the first part of that test to run:

```ruby
irb(main):001:0> File.symlink('C:/SymlinkTest/a.txt', 'C:/SymlinkTest/e.txt')
NotImplementedError: symlink unsupported or native support failed to load
        from org/jruby/RubyFile.java:1029:in `symlink'
        from (irb):1:in `evaluate'
        from org/jruby/RubyKernel.java:1079:in `eval'
        from org/jruby/RubyKernel.java:1479:in `loop'
        from org/jruby/RubyKernel.java:1242:in `catch'
        from org/jruby/RubyKernel.java:1242:in `catch'
        from C:/jruby-1.7.21/bin/jirb:13:in `(root)'
```

I wonder if it has anything to do with running on 64-bit hardware?

**Comment by dometto** [comment]
I cant imagine the symlinks are essential to gollums functionality. Can't we just rewrite the test to not use them, or would that blow things up?

**Comment by bartkamphorst** [comment]
Well, they are currently supported, so we do need tests for them. Also Windows has symlinks, so why shouldn't Ruby/JRuby be able to deal with them properly?

**Comment by dometto** [comment]
Symlink support is nice, of course, but I'd reason the other way: *if* jruby/windows isn't able to handle them, then don't support them on that platform. We could just skip the test on Windows?

**Comment by bartkamphorst** [comment]
Sure, we can skip the test on Windows for the time being. I thought you were proposing to drop symlink support altogether or at least stop testing it.

**Comment by dometto** [comment]
On 26-08-15 18:03, Bart Kamphorst wrote:
> Sure, we can skip the test on Windows for the time being. I thought 
> you were proposing to drop symlink support altogether or at least stop 
> testing it.
I might have thought that for a moment before you convinced me otherwise. :)

**Comment by bartkamphorst** [comment]
Fair enough. :+1: @techwiz24 It might be worthwhile anyway to get the JRuby team involved if you're interested in doing some testing on Windows. I'm sure they could appreciate some feedback from Windows users.

**Comment by techwiz24** [comment]
As an [update](https://github.com/jruby/jruby/issues/3287#issuecomment-137577341) from the `jruby` guys, it seems like they're just marking `File.readlink` as `NotImplemented`.

**Comment by bartkamphorst** [comment]
Thanks @techwiz24 for the update. :+1:

**Comment by dometto** [comment]
Small update: we're hoping that https://github.com/gollum/gollum-lib/pull/218 and https://github.com/gollum/gollum-lib/pull/249 will solve many of the Windows issues when they are merged/released into `v5.x`, since they deal with some of the underlying messyness concerning filenames.

**Comment by nlowe** [comment]
It would appear the `rake build` task isn't compatible with windows:

```powershell
C:\Users\Nathan\projects\gollum [5.x ≡]> rake build
Updated gollum.gemspec
mkdir -p pkg
gem build gollum.gemspec
Invalid gemspec in [gollum.gemspec]: undefined local variable or method `s' for Gem::Specification:Class
ERROR:  Error loading gemspec. Aborting.
rake aborted!
Command failed with status (1): [gem build gollum.gemspec...]
C:/Users/Nathan/projects/gollum/Rakefile:130:in `block in (root)'
c:\jruby-9.2.0.0\bin\rake:23:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

This created two directories, `.\-p` and `.\pkg`. If I comment out the shell call to `mkdir` I get the same gemspec error when trying to build. With debug:

```powershell
C:\Users\Nathan\projects\gollum [5.x ≡ +0 ~2 -0 !]> gem build --debug .\gollum.gemspec
NOTE:  Debugging mode prints all exceptions even when rescued
Invalid gemspec in [.\gollum.gemspec]: undefined local variable or method `s' for Gem::Specification:Class
ERROR:  Error loading gemspec. Aborting.
Exception `Gem::SystemExitException' at C:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/user_interaction.rb:394 - Exiting RubyGems with exit_code 1
Exception `Gem::SystemExitException' at C:/jruby-9.2.0.0/lib/ruby/stdlib/rubygems/user_interaction.rb:394 - Exiting RubyGems with exit_code 1
```

I'll be honest ruby isn't my wheelhouse so I'm not exactly sure what need tweaking.

**Comment by nlowe** [comment]
I think this has something to do with line endings. If I force `gollum.gemspec` to use `LF` instead of `CRLF` I get much further:

```bash
C:\Users\Nathan\projects\gollum [5.x ≡ +0 ~2 -0 !]> rake build
Updated gollum.gemspec
gem build gollum.gemspec
WARNING:  pessimistic dependency on kramdown (~> 1.9.0) may be overly strict
  if kramdown is semantically versioned, use:
    add_runtime_dependency 'kramdown', '~> 1.9', '>= 1.9.0'
WARNING:  pessimistic dependency on shoulda (~> 3.5.0, development) may be overly strict
  if shoulda is semantically versioned, use:
    add_development_dependency 'shoulda', '~> 3.5', '>= 3.5.0'
WARNING:  pessimistic dependency on twitter_cldr (~> 3.2.0, development) may be overly strict
  if twitter_cldr is semantically versioned, use:
    add_development_dependency 'twitter_cldr', '~> 3.2', '>= 3.2.0'
WARNING:  pessimistic dependency on mocha (~> 1.1.0, development) may be overly strict
  if mocha is semantically versioned, use:
    add_development_dependency 'mocha', '~> 1.1', '>= 1.1.0'
WARNING:  pessimistic dependency on test-unit (~> 3.1.0, development) may be overly strict
  if test-unit is semantically versioned, use:
    add_development_dependency 'test-unit', '~> 3.1', '>= 3.1.0'
WARNING:  pessimistic dependency on webrick (~> 1.3.1, development) may be overly strict
  if webrick is semantically versioned, use:
    add_development_dependency 'webrick', '~> 1.3', '>= 1.3.1'
WARNING:  See http://guides.rubygems.org/specification-reference/ for help
  Successfully built RubyGem
  Name: gollum
  Version: 5.0.1b
  File: gollum-5.0.1b.gem
mv gollum-5.0.1b.gem pkg
rake aborted!
Command failed with status (127): [mv gollum-5.0.1b.gem pkg...]
C:/Users/Nathan/projects/gollum/Rakefile:131:in `block in (root)'
c:\jruby-9.2.0.0\bin\rake:23:in `<main>'
Errno::ENOENT: No such file or directory - mv
C:/Users/Nathan/projects/gollum/Rakefile:131:in `block in (root)'
c:\jruby-9.2.0.0\bin\rake:23:in `<main>'
Tasks: TOP => build
(See full trace by running task with --trace)
```

I'm able to then install the gem

**Comment by bartkamphorst** [comment]
@LuckX Which version of gollum are you trying to run?

**Comment by LuckX** [comment]
> @LuckX Which version of gollum are you trying to run?

PS F:\wiki> gollum --v
Gollum 4.1.4

**Comment by LuckX** [comment]
> @LuckX Which version of gollum are you trying to run?

and my operation system is windows server 2008 R2 standard

**Comment by bartkamphorst** [comment]
> Gollum 4.1.4

@LuckX That's your problem right there: Windows will only be supported from `5.x` onwards.

**Comment by dometto** [comment]
Just to make sure: you can checkout the `5.x` development branch now, but it may eat your data. (Or anyway it may throw errors in weird places.)

**Comment by LuckX** [comment]
> > Gollum 4.1.4
> 
> @LuckX That's your problem right there: Windows will only be supported from `5.x` onwards.

I download zip file(gollum-5.x) from github, and how to install it on my windows system.

**Comment by dometto** [comment]
@nlowe  or anyone else with a ruby install on Windows: could you help me to verify that the following code returns the same on Windows as on *nix?
```ruby
2.4.1 :001 > require 'pathname'
 => true 
2.4.1 :002 > Pathname.new('/').cleanpath.to_s
 => "/" 
```
We're now using `Pathname` under the hood to calculate paths relative to the repository too in gollum, and I just want to make sure `Pathname` doesn't return `"C:\"` instead of `"/"` on Windows. Many thanks in advance!

**Comment by dometto** [comment]
> I think this has something to do with line endings. If I force gollum.gemspec to use LF instead of CRLF I get much further:

@nlowe: do we need to do anything about this to make it possible to run on Windows out of the box? Is switching to LF by default an option on *nix?

**Comment by dometto** [comment]
Windows is now fully supported in 5.x!
