### ISSUE TITLE
Differences in preview/render features - Meta Issue

### ISSUE THREAD

**Issue by SkyCrawl** [gollum/gollum#1074]
Gollum currently (v4.0.1) shows some weird behaviour when rendering content, regarding file/page referencing, as follows.

Related issues:
- [ ] [Set base directory for internal use only](https://github.com/gollum/gollum/issues/1052)
- [ ] [Feature request: Support for local files instead of commits](https://github.com/gollum/gollum/issues/1031)
- [ ] [File/page referencing/inclusion for next-gen Gollum](https://github.com/gollum/gollum/issues/999)
- [ ] [Pages named like internal routes don't display](https://github.com/gollum/gollum/issues/630)
- [ ] [Gollum treats org mode differently in a preview than in the final page](https://github.com/gollum/gollum/issues/1004)

My repository (root view):

```
folder/
     TestFolder.md
     img.svg
Test.md
img.svg
```

---

Content of `Test.md`:

```
## IMAGE - root

![image - root](img.svg)

## IMAGE - subfolder

![image - subfolder](folder/img.svg)

## IMAGE - global

[[img.svg]]
```

Behaviour of `Test.md`:
- Page view correctly displays all images.
- Livepreview doesn't display ANY of the images.
- Livepreview's "preview" feature only displays the last (global) image tag.

---

Content of `TestFolder.md`:

```
## IMAGE - absolute

![image - subfolder](/folder/img.svg)

## IMAGE - relative

![image - root](img.svg)
```

Behaviour of `TestFolder.md`:
- Page view correctly displays all images.
- Livepreview only displays the relative (second) image.
- Livepreview's "preview" feature only displays the absolute (first) image.

**Comment by dometto** [comment]
We're ditching the existing livepreview mode in `5.x`, so closing this. Of course these are issues that should be addressed if we end up implementing a version of livepreview in the default editor.
