### ISSUE TITLE
5.0 Release Todo

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1400]
Work on 5.0 is evolving steadily. This is to document various tasks that still need to be performed before we can cut the release. Any help, also with documentation, welcome!

- [x] Resolve the remaining issues under the [5.x milestone](https://github.com/gollum/gollum/milestone/9)
- [x] Remove references to grit in gollum
- [x] Resolve the remaining issues under the [corresponding milestone](https://github.com/gollum/gollum-lib/milestone/3)  for `gollum-lib`
- [x] Update the following files in the root of the repository:
  - [x] `ISSUE.md`
  - [x] `HISTORY.md`
  - [x] `README.md`
- [x] Update the project wiki (remove any old information on limitations, security, etc., and update information on new features and funcationality that's currently in the wiki [Release Notes](https://github.com/gollum/gollum/wiki/5.0-release-notes))
- [x] Compile and package static assets, making sure they run out of the box
  - [x] Review and cleanup image assets
- [x] Release new version of the adapters
- [x] Release new version of gollum-lib
  - [x] Set adapter dependencies correctly in `gemspec` and `Gemfile`
  - [x] Set default adapter correctly
- [x] Release new version of gollum
  - [x] Set adapter and `gollum-lib` dependencies correctly in `gemspec` and `Gemfile`
  - [x] Test the static assets with a `gem build; gem install`
  - [x] Check adapter selection in tests
  - [x] Review/cleanup licenses

**Comment by dometto** [comment]
It's done!
