### ISSUE TITLE
6.0 Release Todo

### ISSUE THREAD

**Issue by dometto** [gollum/gollum#1891]
- [x] Release `gollum-lib v6.0` and make `gollum` depend on it 
- [x] Resolve all issues in the milestone
- [x] Update LATEST_CHANGES.md
- [x] Write release notes in wiki
- [x] Update Readme to reflect latest command line options
- [x] Update [documentation](https://github.com/gollum/gollum/wiki/Sample-config.rb#sample) to reflect latest `wiki_options`
- [x] Compile static assets
- [x] Remove mathjax from `docker-run.sh` as we have  [deprecated](https://github.com/gollum/gollum/blob/master/docker-run.sh#L18) it

**Comment by dometto** [comment]
If anyone has anything they're working on that they'd like to get into the next release, please add it to the milestone :)

**Comment by dometto** [comment]
Release notes here: https://github.com/gollum/gollum/wiki/6.0-Release-Notes

**Comment by almereyda** [comment]
The milestone for v6 only lists one more issue. Is this nearing completion?

* [Issues · gollum/gollum](https://github.com/gollum/gollum/issues?q=is%3Aopen+is%3Aissue+milestone%3A6.0)
* 1857

I'm asking, because the original post above lists some more changes to be ticked off.
